openapi: 3.0.0
info:
  title: BRMH LLM SERVICE
  version: 1.0.0
  description: LLM-powered schema generation for BRMH

paths:
  /llm/generate-schema:
    post:
      summary: Generate schema from prompt using LLM
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  example: "Generate a JSON schema for a project management app with users, projects, tasks, and comments."
      responses:
        '200':
          description: Generated schema
          content:
            application/json:
              schema:
                type: object
                properties:
                  schema:
                    type: object
                  llm_output:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /llm/generate-schema/stream:
    post:
      summary: Generate schema from prompt using LLM (streaming)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  example: "Generate a JSON schema for a project management app with users, projects, tasks, and comments."
      responses:
        '200':
          description: Streamed generated schema
          content:
            text/event-stream:
              schema:
                type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /llm/templates:
    get:
      summary: List all prompt templates
      responses:
        '200':
          description: List of templates
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: { type: string }
                    name: { type: string }
                    context: { type: string }
                    message: { type: string }
    post:
      summary: Save a new prompt template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                context: { type: string }
                message: { type: string }
      responses:
        '201':
          description: Template saved

  /llm/history:
    get:
      summary: List LLM output history
      responses:
        '200':
          description: List of history items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: { type: string }
                    prompt: { type: string }
                    output: { type: string }
                    timestamp: { type: string }
    post:
      summary: Save LLM output history
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt: { type: string }
                output: { type: string }
      responses:
        '201':
          description: History saved 