name: Deploy to EC2

on:
  push:
    branches: [ main ]  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Updated to your region

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-34-199-78-49.compute-1.amazonaws.com
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/brmh-backend
          git pull origin main
          npm install
          pm2 restart all  # If you're using PM2 for process management 