name: Deploy to EC2

on:
  push:
    branches: [ main ]  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-34-199-78-49.compute-1.amazonaws.com
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Debug: Print current directory and contents
          pwd
          ls -la
          
          # Navigate to the correct directory
          cd /home/ec2-user/brmh-backend
          
          # Debug: Print git status
          git status
          
          # Fetch and pull changes
          git fetch origin
          git pull origin main
          
          # Debug: Print npm version and install dependencies
          npm -v
          npm install
          
          # Debug: Check PM2 status
          pm2 list
          
          # Restart the application
          pm2 restart all
          
          # Debug: Print final status
          echo "Deployment completed"
          git status
          pm2 list 